version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.11.1

    steps:
      - checkout

      - run:
          name: Run linter (flake8)
          command: |
            pip install flake8
            flake8 .

      - run:
          name: Install dependencies
          command: make deps

      - run:
          name: Run tests
          command: make test
          
       - run: make docker_build

workflows:
  basic:
    jobs:
      - build-and-test
