version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01

    steps:
      - checkout

      # Dodanie lintera
      - run:
          name: Run linter (flake8)
          command: |
            pip install flake8
            flake8 .

      # Instalacja zależności
      - run:
          name: Install dependencies
          command: make deps

      # Uruchomienie testów
      - run:
          name: Run tests
          command: make test

workflows:
  basic:
    jobs:
      - build-and-test
